#!/usr/bin/env bash

# Create our VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region us-east-1 \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-test123}]" \
--query Vpc.VpcId \
--output text)

echo "VPC_ID=$VPC_ID"

# Create an IGW

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW_ID=$IGW_ID"

# Attach an IGW

aws ec2 attach-internet-gateway --internet-gateway-id '' --vpc-id ''

# Create a new Subnet

# Explicitly associate subnet

# add a reout for our RT to our IGW