#!/usr/bin/env bash


if [ -z "$1" ]; then
    echo "Argument not provided"
else
    export VPC_ID="$1"
fi

if [ -z "$2" ]; then
    echo "Argument not provided"
else
    export IGW_ID="$2"
fi

if [ -z "$3" ]; then
    echo "Argument not provided"
else
    export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
    echo "Argument not provided"
else
    export RT_ID="$4"
fi

# Detach the IGW

aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Delete the IGW

aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

# Dis-associate the subnet

ASSOC_ID=$(aws ec2 describe-route-tables \
--filters "Name=association.subnet-id,Values=$SUBNET_ID" \
--query "RouteTables[].Associations[?SubnetId=='$SUBNET_ID'].RouteTableAssociationId[]" \
--output text)

echo "ASSOC_ID:$ASSOC_ID"

aws ec2 disassociate-route-table --association-id $ASSOC_ID

# Delete subnet

aws ec2 delete-subnet --subnet-id $SUBNET_ID

# Delete Route table

aws ec2 delete-route-table --route-table-id $RT_ID

# Delete VPC

aws ec2 delete-vpc \
--vpc-id $VPC_ID